### ISSUE TITLE
New Query object needed

### ISSUE THREAD

**Issue by imedina** [opencb/datastore#16]
To model queries and filters a new Query objects is needed, this must extend ObjectMap.

**Comment by j-coll** [comment]
[Query](https://github.com/opencb/datastore/blob/develop/datastore-core/src/main/java/org/opencb/datastore/core/Query.java) class extends [ObjectMap](https://github.com/opencb/datastore/blob/develop/datastore-core/src/main/java/org/opencb/datastore/core/ObjectMap.java) and accepts a list of QueryParams. 
Static method Query::validate, checks that all keys inside the query are from the same QueryParam and with the correct type.
